flask/tracking/user/forms.py
from flask.ext.wtf import Form
from wtforms import TextField, PasswordField, BooleanField, SubmitField
from wtforms.validators import Required

from .model import User

class LoginForm(Form):
    password = PasswordField('Password', validators=[Required()])
    submit = SubmitField('Login')

flask/tracking/webapp/forms.py
from flask.ext.wtf import Form
from wtforms import DecimalField, SubmitField
from wtforms.validators import Required

class EntryForm(Form):
  qty = DecimalField('Qty', places=1, rounding=None, validators=[Required()])
  submit = SubmitField('Submit')

flask/tracking/__init__.py
from flask import Flask, redirect, url_for

app = Flask(__name__)
app.config.from_object('config')

# Extensions
from celery import Celery
from flask.ext.babel import Babel
from flask.ext.login import LoginManager
from flask.ext.mail import Mail 
from flask.ext.sqlalchemy import SQLAlchemy
babel = Babel(app)
celery = Celery()
celery.config_from_object(app.config)
login_manager = LoginManager()
login_manager.login_view = 'user.login'
login_manager.login_message = None
login_manager.setup_app(app)
mail = Mail(app)
db = SQLAlchemy(app)

# Blueprints
from .webapp import webapp
from .user import user
from .api import api
for bp in [webapp, user, api]:
  app.register_blueprint(bp)

@app.route('/')
def index():
  return redirect(url_for('webapp.entry'))

flask/tracking/api/__init__.py
from .views import api

flask/tracking/api/views.py
from datetime import datetime
from dateutil import parser
from dateutil import tz
from os import listdir, makedirs, path
from flask import Blueprint, abort, jsonify, request, send_file
from flask.ext.login import login_required
from werkzeug import secure_filename

from .. import app, db
from ..user.model import User
from .model import Activity, Weight

api = Blueprint('api', __name__, url_prefix='/api')

#@app.before_request
#def log():
#  app.logger.debug(request.headers)
#  app.logger.debug(request.form)
#  app.logger.debug(request.files)

@api.route('/upload', methods=['POST'])
def upload():
  # Check Authorization
  auth = request.authorization
  user = User.authorize(auth.username, auth.password) if auth else None
  if user is None:
    abort(401)
  # Save the file; process the file
  file = request.files['file']
  if file:
    timestamp = parser.parse(request.values['datetime'])
    filename = secure_filename(file.filename)
    dir = app.config['UPLOAD_FOLDER']
    if not path.exists(dir):
      makedirs(dir)
    filepath = path.join(dir, filename)
    file.save(filepath)
    activity = Activity(timestamp, filepath)
    db.session.add(activity)
    db.session.commit()
  return ''

@api.route('/weight', methods=['POST'])
def add_weight():
  timestamp = request.form.get('datetime')
  if timestamp:
    timestamp = parser.parse(timestamp)
  else:
    timestamp = datetime.now()
  if timestamp.tzinfo is None:
    timestamp = timestamp.replace(tzinfo=tz.tzlocal())
  qty = request.form['qty']
  unit = request.form.get('unit') or 'lb'
  weight = Weight(timestamp, qty, unit)
  db.session.add(weight)
  db.session.commit()
  return ''
  
@api.route('/weight', methods=['GET'])
@login_required
def get_weight():
  start = request.args.get('start')
  if start is not None:
    start = parser.parse(request.args.get('start'))
    if start.tzinfo is None:
      start = start.replace(tzinfo=tz.tzlocal())
    
  end = request.args.get('end')
  if end is not None:
    end = parser.parse(request.args.get('end'))
    if end.tzinfo is None:
      end = end.replace(tzinfo=tz.tzlocal())
  
  return jsonify(weight=[i.serialize for i in Weight.find(start, end)])
  
@api.route('/query')
@login_required
def query():
  # todo: none handling
  start = parser.parse(request.args.get('start'))
  end = parser.parse(request.args.get('end'))
  if start.tzinfo is None:
    start = start.replace(tzinfo=tz.tzlocal())
  if end.tzinfo is None:
    end = end.replace(tzinfo=tz.tzlocal())
  return jsonify(activities=[i.serialize for i in Activity.find(start, end)])
  '''
  dir = app.config['UPLOAD_FOLDER']
  files = [ f for f in listdir(dir) if path.isfile(path.join(dir,f)) ]
  return jsonify({'car' : files})
  '''
  
# http://stackoverflow.com/questions/13706382/how-to-get-static-files-in-flask-without-url-forstatic-file-name-xxx
@api.route('/img/<filename>')
@login_required
def img(filename):
  if '..' in filename or '/' in filename:
    abort(404)
  dir = app.config['UPLOAD_FOLDER']
  return send_file('../' + dir + '/' + filename, mimetype="image/png")

flask/tracking/user/__init__.py
from .views import user

flask/tracking/user/views.py
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask.ext.login import current_user, logout_user, login_user
from flask.ext.mail import Message

from .. import app, db, login_manager
from ..tasks import send_mail
from .model import User
from .forms import LoginForm

user = Blueprint('user', __name__, url_prefix='/user')

@login_manager.user_loader
def load_user(id):
  try:
    return User.query.get(int(id))
  except:
    return None
    
@user.route('/login', methods = ['GET', 'POST'])
def login():
  if current_user.is_authenticated():
    return redirect(url_for('webapp.entry'))
  login_form  = LoginForm()
  if login_form.validate_on_submit():
    user = User.find("phillipwei@gmail.com")
    print(login_form.password.data)
    if user and user.check_password(login_form.password.data):
      login_user(user, remember=True)
      return redirect(request.args.get('next') or url_for('webapp.entry'))
    flash('Wrong email or password')
  return render_template('user/login.html', page_title='Login', login=login_form)

@user.route('/logout', methods = ['GET', 'POST'])
def logout():
  if not current_user.is_authenticated():
    pass
  else:
    logout_user()
  return redirect(url_for('webapp.entry'))

flask/tracking/webapp/__init__.py
from .views import webapp

flask/tracking/webapp/views.py
from flask import Blueprint, render_template, request
from flask.ext.login import current_user, login_required

from .forms import EntryForm
from ..api import api

webapp = Blueprint('webapp', __name__, url_prefix='/app')

@webapp.route('/timeline', methods = ['GET', 'POST'])
@login_required
def timeline():
  return render_template('webapp/timeline.html')
  
@webapp.route('/entry')
@login_required
def entry():
  entry_form  = EntryForm()
  return render_template('webapp/entry.html', page_title='Entry', entry=entry_form)

# exploration -- weight
@webapp.route('/weight')
@login_required
def weight():
  return render_template('webapp/weight.html')

flask/tracking/templates/_base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>{{ page_title }} | Tracking</title>
    <script type="text/javascript" src="/static/jquery-1.9.1.js"></script>
    <link href="/static/css/normalize.css" rel="stylesheet" type="text/css" />
    <link href='//fonts.googleapis.com/css?family=Source+Sans+Pro:200,400,600,800' rel='stylesheet' type='text/css'>
    <link rel="icon" type="image/ico" href="/static/img/favicon.ico">
    {% block head -%}
    {%- endblock %}
  </head>
  <body>
    {% with messages = get_flashed_messages() %}
    {% if messages %}
    <section id='flash'>
      <ul>
      {% for message in messages %}
        <li>{{ message }} </li>
      {% endfor %}
      </ul>
    </section>
    {% endif %}
    {% endwith %}
    {% block body -%}
    {%- endblock %}
  </body>
  {% block script -%}
  {%- endblock %}
</html>

flask/tracking/templates/_formhelpers.html
{% macro render_field(field) %}
<li>
    {% if field.type == 'BooleanField' %}
        {{ field(**kwargs)|safe }}
        {{ field.label(class_="boolean") }}
    {% else %}
        {{ field.label }}
        {{ field(**kwargs)|safe }}
    {% endif %}
    
    {% if field.errors %}
    <ul class='errors'>
    {% for error in field.errors %}
        <li>{{ error }}</li>
    {% endfor %}
    </ul>
    {% endif %}
</li>
{% endmacro %}

flask/tracking/templates/user/login.html
{% from '_formhelpers.html' import render_field %}
{% extends '_base.html' %}

{% block head %}
{{ super() }}
<link href="/static/css/login.css" rel="stylesheet" type="text/css" />
{% endblock %}

{% block body %}
<section id='login' class='absolutecenter'>
  <form method='POST' action='{{ url_for("user.login") }}' name='login' spellcheck='false'>
    {{ login.hidden_tag() }}
    {{ login.password(autofocus="autofocus") }}
    {{ login.submit }}
  </form>
</section>
{% endblock %}

flask/tracking/templates/webapp/entry.html
{% from '_formhelpers.html' import render_field %}
{% extends '_base.html' %}

{% block head %}
{{ super() }}
<link href="/static/css/entry.css" rel="stylesheet" type="text/css" />
{% endblock %}
{% block body %}
<table id='tabs'>
  <tr>
    <td><a href="#">Weight</a></td>
    <td><a href="#">Food</a></td>
  </tr>
</table>

<section id='entry' class='absolutecenter'>
  <form method='POST' action='{{ url_for("api.add_weight") }}' name='entry'>
    {{ entry.hidden_tag() }}
    {{ entry.qty(type="number", autofocus="autofocus", value="180.9", step="0.1") }}
    {{ entry.submit }}
  </form>
</section>

{% endblock %}

flask/tracking/templates/webapp/timeline.html
{% extends '_base.html' %}

{% block head %}
{{ super() }}
<script type="text/javascript" src="/static/jquery.mousewheel.js"></script>
<link href="/static/css/timeline.css" rel="stylesheet" type="text/css" />
{% endblock %}

{% block body %}
<div class="fit">
  <header class="row">
    <section id="timeline_wrapper">
      <div id="loading_wrapper" class="hidden">
        <div id="loading">
          <div id="loading_inner">
          </div>
        </div>
      </div>
      <section id="timeline" class="hidden">
        <div id="ticks">
        </div>
        <div id="colors">
        </div>
        <div id="current_position">
          <span id="marker">
          </span>
          <span id="text">
          </span>
        </div>
      </section>
      <!--
        <div id="colors">
          {% for (c,time) in [("na",480), ("ok",90), ("good", 180)] -%}
          <span class="color_segment {{c}}" style="width: {{time}}px"></span>
          {%- endfor %}
        </div>
      -->
    </section>
  </header>
  <section class="row expand">
    <div class="content">
      <section id="activity">
        <img id="img" src="/static/img/activity_desktop.png">
      </section>
    </div>
  </section>
  <footer class="row">
    <section id="menu">
      <a class="button" href="{{url_for('user.logout')}}">Logout</a>
    </section>
  </footer>
</div>
{% endblock %}

{% block script %}
<script type="text/javascript">
  $("#timeline").mousewheel(function(event, delta) {
    this.scrollLeft -= (delta * 30);
    event.preventDefault();
  });
  
  
  function set_load_pct(pct) {
    $("#loading_inner").width(Math.min(Math.max(0, Math.round(pct * 100)), 100) + "%")
  }
  
  // http://stackoverflow.com/questions/7293306/how-to-round-to-nearest-hour-using-javascript-date-object
  function round_hour_up(date) {
    console.log('rounding up ' + date);
    date.setHours(date.getHours() + 1);
    date.setMinutes(0);
    date.setSeconds(0);
    date.setMilliseconds(0);
    return date;
  }
  
  // http://stackoverflow.com/questions/2707790/get-a-css-value-from-external-style-sheet-with-javascript-jquery
  function get_class_style(parent, element, style){
    var $e = $(element).hide().appendTo(parent);
    val = $e.css(style);
    $e.remove();
    return val;
  }

  var start, end;
  var tick_width = parseInt(get_class_style('#ticks','<span class="hour_segment"></span>','width').replace('px',''));
  console.log('tick width = ' + tick_width);
  
  function HH_to_hh(hours) {
    mod = hours % 12;
    return mod == 0 ? 12 : mod;
  }
  
  function load_timeline() {
    $('#loading_wrapper').removeClass('hidden');
    
    var now = new Date();
    if(start == undefined || end == undefined) {
      end = round_hour_up(now);
      console.log('end = ' + end);
      
      // http://stackoverflow.com/questions/4943088/how-to-subtract-2-hours-from-users-local-time
      hours = Math.ceil($(window).width() / tick_width);
      console.log('hours = ' + hours);
      start = new Date(end.getTime() - hours * 60 * 60 * 1000);
      console.log('start = ' + start);
      
      for (var d = new Date(start); d <= end; d.setHours(d.getHours() + 1)) {
        $('<span class="hour_segment">' + HH_to_hh(d.getHours()) + '</span>').appendTo('#ticks')
      }
      set_load_pct(0.1);
      
      url = "/api/query?start=" + start.toISOString() + "&end=" + end.toISOString();
      console.log('getting = ' + url);
      $.get(url, function(data) {
        console.log(data);
      });
      set_load_pct(0.2);
    }
    
    $('#timeline').removeClass('hidden');
    $('#loading_wrapper').addClass('hidden');
    
  }
  // http://stackoverflow.com/questions/2056555/c-sharp-sunrise-sunset-with-latitude-longitude
  load_timeline();
  
  function date_to_hhmm() {
    hours = d.getHours();
    minutes = d.getMinutes();
    return HH_to_hh(hours) + ':' + (minutes < 10 ? '0' + minutes : minutes) + ' ' + (hours < 12 ? 'AM' : 'PM');
  }
  
  var adj = Math.round($('#current_position').width() / 2);  // point to div center
  console.log('adj = ' + adj);
  function set_time_pos(x) {
    x = x + adj + $("#timeline").scrollLeft();
    console.log('position = ' + x);
    ms_offset = (-0.5 + x / tick_width) * (60 * 60 * 1000);
    console.log('ms_offset = ' + ms_offset);
    d = new Date(start.getTime() + ms_offset);
    console.log('new time = ' + d);
    $("#text").text(date_to_hhmm);
    
    /*
    var i = Math.min(Math.max(0,Math.round(x / 100)),11);
    var new_src = "/static/img/screenshot/" + i + ".bmp";
    if($("#activity img").attr("src") != new_src) {
      $("#activity img").attr("src", new_src);
    }
    $("#text").text(i + ":00 AM");
    */
  }
  
  /*
  function set_time_pos(x) {
    var cur_img = $("#activity img:not(.hidden)");
    var new_img = $("#activity #img_" + Math.min(Math.max(0,Math.round(x / 100)),11));
    if(cur_img != new_img) {
      cur_img.addClass("hidden");
      new_img.removeClass("hidden");
    }
  }
  */

  $("#current_position")
    .mousedown(function(e) {
      console.log('down');
      var start_x = $(this).offset().left,
        x = e.pageX;
      $(window).mousemove(function(e2) {
        var end_x = start_x + e2.pageX - x;
        $('#current_position').offset({left: end_x});
        set_time_pos(end_x);
      });
      e.preventDefault();
    });
  $(window).mouseup(function() {
    $(window).off('mousemove');
  });
  
  // onLoad
  // onResize
</script>
{% endblock %}

flask/tracking/templates/webapp/weight.html
{% extends '_base.html' %}

{% block head %}
{{ super() }}
<script type="text/javascript" src="/static/d3.v3.js"></script>
<script type="text/javascript" src="/static/moment.js"></script>
<link href="/static/css/weight.css" rel="stylesheet" type="text/css" />
{% endblock %}

{% block body %}
<div class='data_table'>
</div>
<div class='data_graph'>
</div>
{% endblock %}

{% block script %}
<script type="text/javascript">
  function table(d) {
    var tbl = d3.select(".data_table").selectAll(".data_entry")
      .data(d)
      .enter()
      .append("div")
      .attr("id", function(d) { return d.id; } )
      .attr("class", "data_entry");
      
      
    tbl.append("span")
      .attr("class", "timestamp")
      .text(function(d) { return moment(d.datetime).local().fromNow(); });
    
    tbl.append("span")
      .attr("class", "qty")
      .text(function(d) { return d.qty.toFixed(2); });
    
    tbl.append("span")
      .attr("class", "unit")
      .text(function(d) { return d.unit; });
  }
  
  function graph(d) {
    var w = 100, h = 100;
    var g = d3.select(".data_graph")
      .append('svg')
      .attr('width', '100%')
      .attr('height', '100%')
      .attr('viewBox', '0 0 100 100')
      .attr('preserveAspectRatio', 'none');
      
    var t = d.map(function(x) { return new Date(x.datetime).getTime(); });
    var t_min = Math.min.apply(null, t);
    var t_max = Math.max.apply(null, t);
    
    var q = d.map(function(x) { return x.qty; });
    var q_min = Math.min.apply(null, q);
    var q_max = Math.max.apply(null, q);
    
    var startTime = g.selectAll('circle')
      .data(d)
      .enter()
      .append('circle')
      .attr('cx', function(d) { return (new Date(d.datetime).getTime() - t_min) * w / (t_max - t_min); })
      .attr('cy', function(d) { return h - (d.qty - q_min) * h / (q_max - q_min); })
      .attr('r', 0.1);
  }
  
  d3.json("/api/weight",
    function(jsonData) {
      table(jsonData.weight.reverse());
      graph(jsonData.weight);
    }
  );
  
</script>
{% endblock %}